/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public int add(int a, int b) {
        return a + b;
    }

    public int sub(int a, int b) {
        return a - b;
    }

    public int multi(int a, int b) {
        return a * b;
    }

    public int division(int a, int b) {
        return a / b;
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        System.out.println(new App().add(10,6));
        System.out.println(new App().sub(6,5));
        System.out.println(new App().multi(10,5));
        System.out.println(new App().division(10,5));

    }
}
